### ISSUE TITLE
Is it possible to run it with hex file?

### ISSUE THREAD

**Issue by vladimir-popov** [tiberiusbrown/Ardens#35]
Hi! Thanks for awesome emulator! Is it possible to specify a hex file on start, not by drag-n-drop?

**Comment by tiberiusbrown** [comment]
Hi! The command line works similar to the [URL parameters](https://github.com/tiberiusbrown/Ardens#creating-a-link-to-a-playable-arduboy-game), with "param=value" syntax, e.g.: `./Ardens file=game.hex`.

Leaving this issue open until I document this in the readme.

**Comment by tiberiusbrown** [comment]
#37
