### ISSUE TITLE
Possibility of making a libretro core for Android

### ISSUE THREAD

**Issue by sakamoto-neko** [tiberiusbrown/Ardens#58]
Firstly thanks for making a libretro core for running Ardens on Windows! I was wondering if it's possible to build a .so libretro core file compatible with Android versions of Retroarch. Thanks in advance!

**Comment by tiberiusbrown** [comment]
Hi! In theory the libretro core should not have specific platform dependencies, but I've not tried to build it for non-desktop platforms. I posted about it in the libretro discord to see if there was any interest in integrating it into their [CI/CD](https://git.libretro.com/libretro) but didn't get much of a response. There is an untested [.gitlab-ci.yml](https://github.com/tiberiusbrown/Ardens/blob/master/.gitlab-ci.yml) that may work with their setup.

**Comment by gouchi** [comment]
@sakamoto-neko The core is now available for Android.

Please use [F-droid version](https://f-droid.org/en/packages/com.retroarch/) and install the core from the core updater.

Thank you @tiberiusbrown  !
