### ISSUE TITLE
Libretro compilation issue on Windows using msys2

### ISSUE THREAD

**Issue by gouchi** [tiberiusbrown/Ardens#67]
Hi,

I tried to compile the core using [msys2](https://docs.libretro.com/development/retroarch/compilation/windows/) 

```
git clone --recursive https://github.com/tiberiusbrown/Ardens
cd Ardens
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DARDENS_LLVM=0 -DARDENS_DEBUGGER=0 -DARDENS_PLAYER=0 -DARDENS_LIBRETRO=1 ..
make -j$(nproc)
```
But I could not launch the core with error failed to load the core.

According to [Dependencies](https://github.com/lucasg/Dependencies), it seems it does not find :
![image](https://github.com/tiberiusbrown/Ardens/assets/7869503/ec1ae99e-9d1e-4720-8292-963e0f0fa56e)

Should not we add `-static-libgcc -static-libstdc++` ?

Thank you.

**Comment by tiberiusbrown** [comment]
Hi, thanks for letting me know. Are you willing to test the [`msys2_static_libgcc`](https://github.com/tiberiusbrown/Ardens/tree/msys2_static_libgcc) branch for me with your MSYS2 install? If it works, I will merge it.

**Comment by gouchi** [comment]
Hi,

I confirm it is working using [msys2_static_libgcc](https://github.com/tiberiusbrown/Ardens/tree/msys2_static_libgcc) branch.

[ardens_libretro.dll](https://files.catbox.moe/oadrfh.dll) if needed.

Thank you.
