### ISSUE TITLE
Libretro : controls nonresponsive when polling behavior set to "Normal" 

### ISSUE THREAD

**Issue by gouchi** [tiberiusbrown/Ardens#69]
Hi,

If you change the latency polling in RA from Settings > Input > Polling behavior to Normal, controls are not responsive.

The other Arduboy Libretro core suffered the same [issue](https://github.com/libretro/arduous/issues/7) which was fixed with this [commit](https://github.com/libretro/arduous/commit/50c1e48084f003dee582ed5f4f5c0f59eb30bc4c).

Thank you.

**Comment by tiberiusbrown** [comment]
Thanks a bunch for this, I was able to reproduce the problem, and it should be fixed in master with #70.

**Comment by gouchi** [comment]
Thank you, I confirm it is fixed with this [commit](https://github.com/tiberiusbrown/Ardens/commit/1d33c377bf7b2ffba667f6c2e0640b84951e7f80).
